version: "3"
services:
  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    networks:
      - todo_network

  app:
    image: node-mevn-app
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/todoVueDB
    networks:
      - todo_network

  frontend:
    image: vue-mevn-app
    ports:
      - "8081:8081"
    environment:
      - VUE_APP_API_URL=http://app:8080/
    depends_on:
      - app
    networks:
      - todo_network

networks:
  todo_network:
    driver: bridge

volumes:
  mongodb_data:
# version: "3"
# services:
#   app:
#     image: node-crud-ejs-app
#     ports:
#       - "8080:8080"
#     environment:
#       - MONGODB_URI=mongodb://host.docker.internal:27017/crudDB
